### ISSUE TITLE
Compile fails on Windows with MSYS2/MinGW

### ISSUE THREAD

**Issue by richboss** [resilar/sqleet#22]
Sqleet compiles fine on a Linux box, but I've had no such luck on Windows. I am trying to compile the current v0.28.0 release from the amalgamation download with MSYS2/MINGW32 on a Windows 10 machine.

> $ gcc sqleet.c shell.c -o sqleet
> sqleet.c:223659:10: schwerwiegender Fehler: sys/syscall.h: No such file or directory
>  #include <sys/syscall.h>
>           ^~~~~~~~~~~~~~~
> Kompilierung beendet.

By way of comparison, the corresponding v3.28 SQLite amalgamation compiles without problems:
> $ gcc sqlite3.c shell.c -o sqlite.exe
> $ ./sqlite.exe -version
> 3.28.0 2019-04-16 19:49:53 (...)

I am not very experienced in compiling C code, so I am stuck here. Are there any preconditions to be met that are not mentioned on the website? I surely hope for an easy solution without elaborate steps ;-)

**Comment by resilar** [comment]
Thanks for reporting the issue. Windows build has been tested with non-MSYS2 MinGW before, which missed this particular compilation error.

I'm not too familiar with MSYS2, but the problem seems to be that MSYS2 emulates POSIX and `sys/syscall.h` included in [crypto.c:L465](https://github.com/resilar/sqleet/blob/2ef09966de7a5c77cf76d31ab635e98f8e4a831/crypto.c#L458-L466) is not a standard POSIX C header (even though Linux, *BSD and Mac ship with the header). A dumb fix is to avoid including `sys/syscall.h` in MSYS2 builds, but that would still result in reading randomness from `/dev/urandom` which requires a full-blown cygwin environment to work (MSYS2 is not sufficient). Thus, the desired behavior on MSYS2 is to use `RtlGenRandom()` WinAPI ([crypto.c:L541](https://github.com/resilar/sqleet/blob/2ef09966de7a5c77cf76d31ab635e98f8e4a831/crypto.c#L541-L552)) to generate random numbers.

Commit  f053e2e fixes this issue by using `RtlGenRandom()` if compile-time macro `_WIN32` **or** `__CYGWIN__` is defined. MSYS2 defines `__CYGWIN__` by default, so the current master should compile out-of-the-box on MSYS2.

If you prefer amalgamations and do not want to wait for the next sqleet release incorporating the fix, then simply clone `master` and run

```
[sqleet]$ ./script/amalgamate.sh <sqleet.c >amalgamation.c
[sqleet]$ ./script/amalgamate.sh <sqleet.h >amalgamation.h
```

... and use the produced `amalgamation.{c,h}` source files. The amalgamate script works fine in MSYS2 shell (although amalgamating `sqleet.c` takes a rather long time, ~40 seconds, on my test MSYS2 environment).

**Comment by richboss** [comment]
Thanks, resilar. Works a treat! :-) And I appreciate your detailed explanations, too.

> A dumb fix is to avoid including sys/syscall.h in MSYS2 builds, ...

This is what I did, innocently, right after opening this issue, when I tinkered with the code. I had to comment out a few lines so that the entropy function returned "read_urandom(buf, n)". This compiled on my box and seemed to work, which made me happy. But I was quite unsure if this was the right way to go about it, and if it might have compromised security somehow.  Glad you found a better solution :-) Thanks again.

**Comment by resilar** [comment]
Interesting that `read_urandom(buf, n)` apparently worked and did not crash the program. Maybe I was wrong and MSYS2 emulates `/dev/urandom` after all. I would have expected that reading `/dev/urandom` either errors out on `open()` or fills read buffer with zeros, therefore triggering `abort()` in `read_urandom()`'s sanity checks.

It is possible that MSYS2's `read_urandom()` compromised your sqleet databases by returning poor pseudorandomness for nonces. However, I cannot confirm or deny this at the moment without further research (**TODO**: Do the research to verify that `read_urandom()` is not broken whatsoever). To err on the safe side, run `VACUUM` or `PRAGMA rekey='...'` on compromised databases using a fixed sqleet version in order to replace any weak nonces in the database file(s) with newly generated strong nonces.


---

Anyway, even if MSYS2's `/dev/urandom` turns out to be secure, `RtlGenRandom()` is still the preferred and more reliable method to generate cryptographically secure pseudorandom numbers on Windows.
