### ISSUE TITLE
A strange bug with rekey.

### ISSUE THREAD

**Issue by johnfound** [resilar/sqleet#29]
I am using PRAGMA to call the rekey function.

After decrypting the database with `pragma rekey='';`, the following `pragma rekey='somenewkey';` almost always fails.

In order to encrypt the database again, I must reopen the database, or to execute `pragma rekey='';` several times. After one of these, the following `pragma rekey='somenewkey'` successfully encrypts the  database. 

On encrypted database `pragma rekey=''` always successfully decrypts the database.

On all these commands there is no error returned by sqlite3_step(). The only difference is that the successful rekey (with nonempty key) returns SQLITE_ROW and the unsuccessful returns SQLITE_DONE.

On the other hand, rekey with empty key (decrypt database) always return SQLITE_DONE, but still decrypts the database. 

Also the bug is related on the decrypt operation (rekey with empty string value). When calling rekey for re-encrypting the database with new key, it always success.

**Comment by resilar** [comment]
Unfortunately I am unable to reproduce the issue with the latest version of sqleet.

The described issue looks *suspiciously* similar to _"Cannot set key again if having removed key"_ #26 fixed two weeks ago. **Can you confirm that you are running the latest master of sqleet?** The #26 fix should also be included in the *updated* v0.29.0 release package if downloaded no longer than a fortnight ago (sorry about the ambiguous v0.29.0 version number, the process of publishing sqleet bugfix releases needs some thought).

If this turns out to be another bug, my prime suspects are failing `sqlite3RekeyVacuum()` call on [sqleet.c:575](https://github.com/resilar/sqleet/blob/06e922a71dda1ab7ee5c16c8f9e0fa2924b433ac/sqleet.c#L575) due to `size_hook()` and improperly initialized `Codec` structure. If possible, please provide a sample database file for triggering the bug. It helps *a lot* in investigating and fixing the bug.

>Minor complaint: sqlite3_rekey(DB, 0, 0) fails with SQLITE_ERROR. IMO, when nKey==0 the zKey should be ignored.

I fully agree. The oversight is the result of the official SQLite3 shell never calling rekey with `zKey == NULL` (even if rekeying with an empty string). This has now been fixed in master. Thanks again for improving sqleet.

**Comment by johnfound** [comment]
> The #26 fix should also be included in the updated v0.29.0 release package if downloaded no longer than a fortnight ago (sorry about the ambiguous v0.29.0 version number, the process of publishing sqleet bugfix releases needs some thought).

Yes, that was exactly the case! I have downloaded v0.29.0, but unfortunately the non-fixed version. Later didn't download again, because it was the same version 0.29.0;

After downloading the latest changes from the master and compiling all bugs disappeared. Thanks.
