### ISSUE TITLE
Error compiling in Xcode - Clang

### ISSUE THREAD

**Issue by rapraor** [resilar/sqleet#34]
Hi!

I am a self-teaching programmer, no commercial, just hobbyist and smalls programs to my hobbies or helping automating some processes on my job. I learn a lot from people posting source codes, so I would like to thank you first of all.

I am in love with sqlite since I found it was a cross-platform and embeddable database years ago, and I have been looking for a way to encrypt sqlite db since then. I have come to sqleet, but when trying to compile it in Xcode found lots of errors preventing me from compiling it.

I have downloaded the amalgamation of sqlite source from its web, dropped it in my project of c++ console, and just tried to open and close a connection to a db. It compiled perfectly and showed "It worked!!", just with 73 warnings (several MIN and MAX macros duplicated with <sys/format.h>, some loose integer precision, and few code will never be executed):

`

#include "../SQLite3/sqlite3.h"

int main(int argc, const char * argv[]) {
    sqlite3 *db;
    if(sqlite3_open("/Users/Raul/Desktop/Aviacion.db", &db)==SQLITE_OK) {
        std::cout << "It worked!!" << std::endl;
    }
    sqlite3_close(db);
    
    return 0;
}

`

A continuation I have done, manually, my own sqleet.c amalgamation with sqlite3.c downloaded from sqlite's web that worked in previous example. To my surprise, I get 83 warnings and lots of errors (Xcode stop showing me at 20 errors) on sqlite3.c part of the amalgamation of sqleet.c. An example of errors were:

> assigning to sqlite3_mutex* from incompatible void*
>  assigning to char* from incompatible type void*
>  assigning to struct SrcList_item* (aka SrcList_item* from incompatible type SrcList::SrcList_item*
>  cannot initialize a variable of type unsigned char* with an lvalue of type void*

It is very strange, as it was the same part of sqlite that was compiling before, and give same errors as the almagalmation done via almagalmation.sh of sqleet.

¿any clues?

**Comment by resilar** [comment]
I do not have Xcode myself, but I can confirm that clang compiles sqleet fine on Linux. Some guesses:

* Include amalgamated *sqleet* header `sqleet.h` instead of `sqlite3.h` from SQLite3 source
* Try [pre-amalgamated sqleet release](https://github.com/resilar/sqleet/releases) just in case there's some problem with your custom amalgamation. There have been some shell script compatibility issues between Linux and OS X, which might explain broken `amalgamate.sh` output.
* Make sure Xcode compiles only the amalgamated sqleet source. Compiling both SQLite3 amalgamation `sqlite3.c` and sqleet amalgamation `sqleet.c` at the same time does not work.

If nothing works, verify that the project compiles using plain SQLite3 without sqleet encryption extension. If the compilation fails only with sqleet, then I'd check the compiler commands that Xcode runs when compiling the project. I am not familiar with Xcode, but the executed commands are most likely available in some log somewhere after an unsuccessful compilation.

Report back and, if possible, attach log of the commands executed by Xcode when compiling the code.

**Comment by rapraor** [comment]
Thank you for your time.

As I told you, I tried to compile plain sqlite3 and worked perfectly, and used that plain sqlite3 to make my own manual amalgamation which failed compiling.

But, I have done as you said, downloaded sqleet pre-amalgamation from GitHub, and compiled with no trouble on standard Xcode console template.

I am now getting fun playing around.

Thank you!
