### ISSUE TITLE
Possible SQLite3 compatibility issue

### ISSUE THREAD

**Issue by utelle** [resilar/sqleet#8]
I came across your SQLite3 encryption extension by chance. I'm very interested in adopting your encryption scheme for my own SQLite3 encryption extension (packaged with [wxSQLite3](https://github.com/utelle/wxsqlite3)), since nowadays one has to face increasing security requirements.

However, in your implementation might be a possible compatibility issue. According to the documentation of the official [SQLite Encryption Extension (SEE)](https://www.sqlite.org/see/doc/trunk/www/readme.wiki) (at the bottom of the page) some bytes of the first database page are not encrypted:

> Bytes 16 through 23 of the database are unencrypted. Thus, you can always check to see how much nonce is being used, even on an encrypted database file, just by looking at byte 20. It is recommended that any product that uses encryption check this byte to make sure it is being set to 4 or 12 or 32 and not 0. 

And indeed, the database header is read in the function `sqlite3BtreeOpen` before the enryption codec gets a chance to decrypt page 1. Probably this does no harm - at least I did not experience actual problems up to now -, but maybe bytes 16 through 23 should be saved unencrypted to increase compatibility with the official SQLite3 version.

**Comment by utelle** [comment]
It should be quite easy to adjust **sqleet** to always let bytes 16 to 23 unencrypted. All that is required is to offset to byte 24 on encrypting or decrypting page 1. However, this is an incompatible change, of course.

**Comment by resilar** [comment]
Implemented as a compile-time option instead of a default setting since having encrypted databases that are indistinguishable from random is a big selling point (in addition, the compatibility break would suck).

>And indeed, the database header is read in the function sqlite3BtreeOpen before the enryption codec gets a chance to decrypt page 1. Probably this does no harm

The only problem I have experienced is that the user has to explicitly set page size before the encryption key if the database uses a non-standard page size (e.g., `PRAGMA page_size=512`). This is also the reason why, in the latest version, `BYTE16TO23_UNENCRYPTED` of #11 has been replaced with the more flexible `SKIP_HEADER_BYTES`: Another valid use case is to keep only the first 18 bytes unencrypted so that `sqlite3BtreeOpen` can read & set the page size without leaking information about the following 6 bytes.

**Comment by utelle** [comment]
> Implemented as a compile-time option instead of a default setting since having encrypted databases that are indistinguishable from random is a big selling point (in addition, the compatibility break would suck).

In fact, only 8 bytes of the database header stay unencrypted, since the first 16 bytes are replaced by the key salt (random data), and only 3 of the 8 unencrypted bytes have currently absolutely fixed values.

Regarding the compatibility break I faced the same problem with wxSQLite3. I solved it by converting from the old scheme to the new scheme on the fly. However, it's up to you how to handle it in sqleet.

Maybe it is unlikely that SQLite3 behaviour in respect to the 8 header bytes 16 to 23 will change in the future. That is, maybe it would be sufficient to leave bytes 16 & 17 unencrypted, so that SQLite3 is able to detect the page size automatically without user intervention. Personally I prefer to not being forced to use a pragma to change the page size if the database does not use the default page size.
